### ISSUE TITLE
Game gets stuck every 2 seconds

### ISSUE THREAD

**Issue by marty1912** [iAM-Linus/event-bus-plugin#1]
Hi :)
Thank you for creating this great asset. 
I tried it and noticed that performance was terrible. 
Every 2 sec the game completely froze and did not respond at all. 
I actually managed to find the problem:
EventBusIngameOverview.gd: _process

In this function you wait for the timeout of the timer to execute the update function.
This results in a lot of waiting _process calls to be executed at once as soon as the timeout occurs.

I fixed this by creating a seperate function and waiting in a while loop instead of _process.

looks something like this (_process is completely removed from EventBusIngameOverview.gd) : 
.....
	timer.one_shot = false
	timer.wait_time = 2.0
	add_child(timer)
	update_overview_not_so_often()

func update_overview_not_so_often():
	while(true):
		await get_tree().create_timer(2.0).timeout
		print("updating overview...")
		update_overview()

I think this is a rather easy fix. 
After this I did not have any performance problems anymore

Please let me know if you need any more info/help and thank you again for making this asset :)

**Comment by iAM-Linus** [comment]
@edit: Just noticed that I didnt remove the _process function in the last fix so just pushed a new update again T.T
Should work now though!

Hey there!
Thanks, glad it can be of use :)

I just pushed an update that hopefully fixes the issue. Try it and let me know if it works

**Comment by SebMatDo** [comment]
Hi, I also noted that but I were busy.
My solution was very similar to yours, I deleted processs and add 

timer.timeout.connect(update_overview)
timer.start(2)

Also I did that if the overview wasn't visible it didn't use resources
func update_overview() -> void:
	if !is_visible: return 
        ...code...

**Comment by Zaglik** [comment]
Hey man, I think you forgot to update the download in the Godot Asset Library, it still has that performance bug.

**Comment by MoogieOuttaMyDepth** [comment]
Oh thank god this thread existed, I was afraid this was only happening to me and I had absolutely no idea how to troubleshoot it. Yes, the Godot Asset Library version still has this bug. Update would be appreciated. :)

Edit: Unfortunately, even having copied over the script from this repo into my project, I still get a stutter of about 0.1 seconds every couple of seconds. I only have a couple of signals implemented right now, so this performance is completely untenable.

**Comment by SebMatDo** [comment]
@MoogieOuttaMyDepth Have you tried my return clausule to avoid using resources if you aren't using the overview?
That stutter is (almost) acceptable for debugging purpouses but no for released games

**Comment by jgardner8** [comment]
This PR should fix it https://github.com/iAM-Linus/event-bus-plugin/pull/2
